### ISSUE TITLE
The Transformer Head of SeqTrack

### ISSUE THREAD

**Issue by Tchuanm** [microsoft/2D-TAN#103]
Hi, @chenxin-dlut 

with I check the code and find there also exist a method which can choose the model: fed seatch and tempalte patches into Decoder. 
Have you do the ablation of fed  template-search patches together vs. search patches only into Deooder. 
The performance will reduce obviously or not for the former ? 

Thanks for your work.

**Comment by chenxin-dlut** [comment]
Hi,
This method performs similar to our default method, you can find the results in the ablation study of our paper.

**Comment by chenxin-dlut** [comment]
Hi,
This method performs similar to our default method, you can find the results in the ablation study of our paper.
