### ISSUE TITLE
Argument Clarification

### ISSUE THREAD

**Issue by AmeenAli** [microsoft/2D-TAN#12]
Hi,
Can you clarify more about the TARGET_STRIDE argument? <br>
Thanks

**Comment by Sy-Zhang** [comment]
It's the output downsample rate in terms of input. For example, if there are NUM_SAMPLE_CLIPS input clips, then the height and width of the output score map should be NUM_SAMPLE_CLIPS//TARGET_STRIDE.

**Comment by AmeenAli** [comment]
> It's the output downsample rate in terms of input. For example, if there are NUM_SAMPLE_CLIPS input clips, then the height and width of the output score map should be NUM_SAMPLE_CLIPS//TARGET_STRIDE.

Thanks,
can you tell for how many epochs training was done? because I am still not able to reproduce the same results mentioned in the paper, Thanks

**Comment by Sy-Zhang** [comment]
> > It's the output downsample rate in terms of input. For example, if there are NUM_SAMPLE_CLIPS input clips, then the height and width of the output score map should be NUM_SAMPLE_CLIPS//TARGET_STRIDE.
> > @Sy-Zhang
> > Thanks,
> > can you tell for how many epochs training was done? because I am still not able to reproduce the same results mentioned in the paper, Thanks

The epoch for training is defined as MAX_EPOCH, which is set to 100 for all datasets.
