### ISSUE TITLE
Loss equation question 

### ISSUE THREAD

**Issue by AmeenAli** [microsoft/2D-TAN#15]
Hi <br>
can you explain the intuition behind the need of scaling the IoU values between 0 and 1 in the loss function?
Thanks

**Comment by Sy-Zhang** [comment]
> Hi
> 
> can you explain the intuition behind the need of scaling the IoU values between 0 and 1 in the loss function?
> Thanks

We would like to make the score map sharper (more discriminative), therefore we scaling the IoU in loss function.
