### ISSUE TITLE
Question about table 2

### ISSUE THREAD

**Issue by AmeenAli** [microsoft/2D-TAN#16]
Hello
Thanks for sharing this amazing work.
I have a question regarding table 2, The original MCN paper didn't publish results on Activitynet Captions dataset, thus I assume you have re-evaluated their model again on this dataset, my question is did you follow their same setting in the sense of dividing each video into 5 seconds segments and thus each moment candidate now composed of any continuous number of segments?
Best

**Comment by Sy-Zhang** [comment]
> Hello
> Thanks for sharing this amazing work.
> I have a question regarding table 2, The original MCN paper didn't publish results on Activitynet Captions dataset, thus I assume you have re-evaluated their model again on this dataset, my question is did you follow their same setting in the sense of dividing each video into 5 seconds segments and thus each moment candidate now composed of any continuous number of segments?
> Best

We didn't implement it. The performance of MCN on ActivityNet Captions is reported in CMIN. We simply copy the result from theirs.
