### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by DW-Lay** [microsoft/2D-TAN#17]
I meet this problem as followes
" RuntimeError: CUDA out of memory. Tried to allocate 1.41 GiB (GPU 0; 11.91 GiB total capacity; 11.04 GiB already allocated; 203.06 MiB free; 121.00 MiB cached)"
 
When i run this program as introduced, Gpu 0 is available.
How can solve this issues? thank you

**Comment by Sy-Zhang** [comment]
> I meet this problem as followes
> " RuntimeError: CUDA out of memory. Tried to allocate 1.41 GiB (GPU 0; 11.91 GiB total capacity; 11.04 GiB already allocated; 203.06 MiB free; 121.00 MiB cached)"
> 
> When i run this program as introduced, Gpu 0 is available.
> How can solve this issues? thank you

Use more GPUs or set smaller batch size.
