### ISSUE TITLE
How long will it take to finish the whole program？

### ISSUE THREAD

**Issue by mysuli2333** [microsoft/2D-TAN#20]
I run the code for ActivityNet Captions dataset and it takes 3 hours for one epoch on one RTX 2080Ti. I want to confirm the time and the number of epoches.

**Comment by Sy-Zhang** [comment]
> I run the code for ActivityNet Captions dataset and it takes 3 hours for one epoch on one RTX 2080Ti. I want to confirm the time and the number of epoches.

I run it on a single v100. It takes about 1 hour per epoch and 1~2 days to achieve the best performance.

**Comment by Sy-Zhang** [comment]
> I run the code for ActivityNet Captions dataset and it takes 3 hours for one epoch on one RTX 2080Ti. I want to confirm the time and the number of epoches.

I run it on a single v100. It takes about 1 hour per epoch and 1~2 days to achieve the best performance.

**Comment by Sy-Zhang** [comment]
> I run the code for ActivityNet Captions dataset and it takes 3 hours for one epoch on one RTX 2080Ti. I want to confirm the time and the number of epoches.

I run it on a single v100, it takes about 1 hour per epoch and about 2 days for training.
