### ISSUE TITLE
About LSTM

### ISSUE THREAD

**Issue by MPhone1000** [microsoft/2D-TAN#23]
Hi! 

In your paper released in Arxiv, it said that 
>we sequentially feed the word embeddings into a three-layer bidirectional LSTM network.

However, in the experiment setting files under the `experiments` folder, `TAN/FUSION_MODULE/PARAMS/LSTM/BIDIRECTIONAL` is all set to `False`.

May I ask the reason of it?

**Comment by Sy-Zhang** [comment]
> Hi!
> 
> In your paper released in Arxiv, it said that
> 
> > we sequentially feed the word embeddings into a three-layer bidirectional LSTM network.
> 
> However, in the experiment setting files under the `experiments` folder, `TAN/FUSION_MODULE/PARAMS/LSTM/BIDIRECTIONAL` is all set to `False`.
> 
> May I ask the reason of it?

This is our mistake. Bidirectional is not used in our experiments. We will update our Arxiv version.

**Comment by MPhone1000** [comment]
Thanks for your reply. ^_^
