### ISSUE TITLE
random seed

### ISSUE THREAD

**Issue by Huntersxsx** [microsoft/2D-TAN#25]
Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
`def set_seed(seed):`
    `random.seed(seed)`
    `np.random.seed(seed)`
    `torch.manual_seed(seed)`
    `torch.cuda.manual_seed(seed)`
    `torch.cuda.manual_seed_all(seed)`
I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?

**Comment by Sy-Zhang** [comment]
The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).

We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.

**Comment by Sy-Zhang** [comment]
> Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
> `def set_seed(seed):`
> `random.seed(seed)`
> `np.random.seed(seed)`
> `torch.manual_seed(seed)`
> `torch.cuda.manual_seed(seed)`
> `torch.cuda.manual_seed_all(seed)`
> I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?

The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).

We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.

**Comment by Huntersxsx** [comment]
> > Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
> > `def set_seed(seed):`
> > `random.seed(seed)`
> > `np.random.seed(seed)`
> > `torch.manual_seed(seed)`
> > `torch.cuda.manual_seed(seed)`
> > `torch.cuda.manual_seed_all(seed)`
> > I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?
> 
> The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).
> 
> We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.

Thanks for your reply~

**Comment by Huntersxsx** [comment]
> > Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
> > `def set_seed(seed):`
> > `random.seed(seed)`
> > `np.random.seed(seed)`
> > `torch.manual_seed(seed)`
> > `torch.cuda.manual_seed(seed)`
> > `torch.cuda.manual_seed_all(seed)`
> > I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?
> 
> The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).
> 
> We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.

Hello! Thanks for your great work, I have experimented with your code on TACoS and Charades datasets you offered in google drive, but I met some problems on ActivityNet dataset. The download sh file in your repository seems invalid, and features on http://activity-net.org/challenges/2016/download.html , do not match with the json file you offered, can you offer some help?

**Comment by Sy-Zhang** [comment]
> > > Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
> > > `def set_seed(seed):`
> > > `random.seed(seed)`
> > > `np.random.seed(seed)`
> > > `torch.manual_seed(seed)`
> > > `torch.cuda.manual_seed(seed)`
> > > `torch.cuda.manual_seed_all(seed)`
> > > I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?
> > 
> > 
> > The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).
> > We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.
> 
> Hello! Thanks for your great work, I have experimented with your code on TACoS and Charades datasets you offered in google drive, but I met some problems on ActivityNet dataset. The download sh file in your repository seems invalid, and features on http://activity-net.org/challenges/2016/download.html , do not match with the json file you offered, can you offer some help?

Could you give more information about the unmatched part? Do you mean the video ids are not matched?

**Comment by Huntersxsx** [comment]
> > > > Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
> > > > `def set_seed(seed):`
> > > > `random.seed(seed)`
> > > > `np.random.seed(seed)`
> > > > `torch.manual_seed(seed)`
> > > > `torch.cuda.manual_seed(seed)`
> > > > `torch.cuda.manual_seed_all(seed)`
> > > > I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?
> > > 
> > > 
> > > The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).
> > > We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.
> > 
> > 
> > Hello! Thanks for your great work, I have experimented with your code on TACoS and Charades datasets you offered in google drive, but I met some problems on ActivityNet dataset. The download sh file in your repository seems invalid, and features on http://activity-net.org/challenges/2016/download.html , do not match with the json file you offered, can you offer some help?
> 
> Could you provide more information about what is not matched?

If I directly use the features on the website  http://activity-net.org/challenges/2016/download.html  , there comes an error
"**KeyError: "Unable to open object (object 'v_PdNb0g36a6U' doesn't exist)"**"
The website notes that

> We reduce the dimensionality of the activations from the second fully-connected layer (fc7) of our visual encoder from 4096 to 500 dimensions using PCA.  The C3D features were extracted every 8 frames

Your paper mentioned that clip T is set to 16 for ActivityNet, how can I use the same feature you mentioned in your paper?

**Comment by Sy-Zhang** [comment]
> > > > > Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
> > > > > `def set_seed(seed):`
> > > > > `random.seed(seed)`
> > > > > `np.random.seed(seed)`
> > > > > `torch.manual_seed(seed)`
> > > > > `torch.cuda.manual_seed(seed)`
> > > > > `torch.cuda.manual_seed_all(seed)`
> > > > > I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?
> > > > 
> > > > 
> > > > The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).
> > > > We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.
> > > 
> > > 
> > > Hello! Thanks for your great work, I have experimented with your code on TACoS and Charades datasets you offered in google drive, but I met some problems on ActivityNet dataset. The download sh file in your repository seems invalid, and features on http://activity-net.org/challenges/2016/download.html , do not match with the json file you offered, can you offer some help?
> > 
> > 
> > Could you provide more information about what is not matched?
> 
> If I directly use the features on the website http://activity-net.org/challenges/2016/download.html , there comes an error
> "**KeyError: "Unable to open object (object 'v_PdNb0g36a6U' doesn't exist)"**"
> The website notes that
> 
> > We reduce the dimensionality of the activations from the second fully-connected layer (fc7) of our visual encoder from 4096 to 500 dimensions using PCA.  The C3D features were extracted every 8 frames
> 
> Your paper mentioned that clip T is set to 16 for ActivityNet, how can I use the same feature you mentioned in your paper?

It seems like the provided features have been modified. Fortunately, I have a backup. You can check the shared google drive link again.

**Comment by Huntersxsx** [comment]
> > > > > > Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
> > > > > > `def set_seed(seed):`
> > > > > > `random.seed(seed)`
> > > > > > `np.random.seed(seed)`
> > > > > > `torch.manual_seed(seed)`
> > > > > > `torch.cuda.manual_seed(seed)`
> > > > > > `torch.cuda.manual_seed_all(seed)`
> > > > > > I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?
> > > > > 
> > > > > 
> > > > > The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).
> > > > > We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.
> > > > 
> > > > 
> > > > Hello! Thanks for your great work, I have experimented with your code on TACoS and Charades datasets you offered in google drive, but I met some problems on ActivityNet dataset. The download sh file in your repository seems invalid, and features on http://activity-net.org/challenges/2016/download.html , do not match with the json file you offered, can you offer some help?
> > > 
> > > 
> > > Could you provide more information about what is not matched?
> > 
> > 
> > If I directly use the features on the website http://activity-net.org/challenges/2016/download.html , there comes an error
> > "**KeyError: "Unable to open object (object 'v_PdNb0g36a6U' doesn't exist)"**"
> > The website notes that
> > > We reduce the dimensionality of the activations from the second fully-connected layer (fc7) of our visual encoder from 4096 to 500 dimensions using PCA.  The C3D features were extracted every 8 frames
> > 
> > 
> > Your paper mentioned that clip T is set to 16 for ActivityNet, how can I use the same feature you mentioned in your paper?
> 
> It seems like the provided features have been modified. Fortunately, I have a backup. You can check the shared google drive link again.

hello, I tried to open the link, but the Activitynet folder seems to be locked, and I don't have the root to download it, I change to other accounts and failed too, can you give me the permission?

**Comment by Sy-Zhang** [comment]
> > > > > > > Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
> > > > > > > `def set_seed(seed):`
> > > > > > > `random.seed(seed)`
> > > > > > > `np.random.seed(seed)`
> > > > > > > `torch.manual_seed(seed)`
> > > > > > > `torch.cuda.manual_seed(seed)`
> > > > > > > `torch.cuda.manual_seed_all(seed)`
> > > > > > > I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?
> > > > > > 
> > > > > > 
> > > > > > The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).
> > > > > > We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.
> > > > > 
> > > > > 
> > > > > Hello! Thanks for your great work, I have experimented with your code on TACoS and Charades datasets you offered in google drive, but I met some problems on ActivityNet dataset. The download sh file in your repository seems invalid, and features on http://activity-net.org/challenges/2016/download.html , do not match with the json file you offered, can you offer some help?
> > > > 
> > > > 
> > > > Could you provide more information about what is not matched?
> > > 
> > > 
> > > If I directly use the features on the website http://activity-net.org/challenges/2016/download.html , there comes an error
> > > "**KeyError: "Unable to open object (object 'v_PdNb0g36a6U' doesn't exist)"**"
> > > The website notes that
> > > > We reduce the dimensionality of the activations from the second fully-connected layer (fc7) of our visual encoder from 4096 to 500 dimensions using PCA.  The C3D features were extracted every 8 frames
> > > 
> > > 
> > > Your paper mentioned that clip T is set to 16 for ActivityNet, how can I use the same feature you mentioned in your paper?
> > 
> > 
> > It seems like the provided features have been modified. Fortunately, I have a backup. You can check the shared google drive link again.
> 
> hello, I tried to open the link, but the Activitynet folder seems to be locked, and I don't have the root to download it, I change to other accounts and failed too, can you give me the permission?

I just uploaded it again, you can try it now.

**Comment by Huntersxsx** [comment]
> > > > > > > > Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
> > > > > > > > `def set_seed(seed):`
> > > > > > > > `random.seed(seed)`
> > > > > > > > `np.random.seed(seed)`
> > > > > > > > `torch.manual_seed(seed)`
> > > > > > > > `torch.cuda.manual_seed(seed)`
> > > > > > > > `torch.cuda.manual_seed_all(seed)`
> > > > > > > > I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?
> > > > > > > 
> > > > > > > 
> > > > > > > The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).
> > > > > > > We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.
> > > > > > 
> > > > > > 
> > > > > > Hello! Thanks for your great work, I have experimented with your code on TACoS and Charades datasets you offered in google drive, but I met some problems on ActivityNet dataset. The download sh file in your repository seems invalid, and features on http://activity-net.org/challenges/2016/download.html , do not match with the json file you offered, can you offer some help?
> > > > > 
> > > > > 
> > > > > Could you provide more information about what is not matched?
> > > > 
> > > > 
> > > > If I directly use the features on the website http://activity-net.org/challenges/2016/download.html , there comes an error
> > > > "**KeyError: "Unable to open object (object 'v_PdNb0g36a6U' doesn't exist)"**"
> > > > The website notes that
> > > > > We reduce the dimensionality of the activations from the second fully-connected layer (fc7) of our visual encoder from 4096 to 500 dimensions using PCA.  The C3D features were extracted every 8 frames
> > > > 
> > > > 
> > > > Your paper mentioned that clip T is set to 16 for ActivityNet, how can I use the same feature you mentioned in your paper?
> > > 
> > > 
> > > It seems like the provided features have been modified. Fortunately, I have a backup. You can check the shared google drive link again.
> > 
> > 
> > hello, I tried to open the link, but the Activitynet folder seems to be locked, and I don't have the root to download it, I change to other accounts and failed too, can you give me the permission?
> 
> I just uploaded it again, you can try it now.

Thank you!!
I saw you uploaded file 'sub_activitynet_v1-3.c3d.hdf5' first, then you uploaded 'activitynet_v1-3.part-*' and 'PCA_activitynet_v1-3.hdf5' files which is the same as the official features on http://activity-net.org/challenges/2017/download.html.
Which feature was used in your paper? I saw the INPUT_SIZE in your activitynet yaml file is set to 500, is that mean you use c3d PCA features as ActivityNet input?

**Comment by Sy-Zhang** [comment]
> > > > > > > > > Hello, did you try to fix the random seed in the code to obtain the same results when running the same code? I made some attempts as follows:
> > > > > > > > > `def set_seed(seed):`
> > > > > > > > > `random.seed(seed)`
> > > > > > > > > `np.random.seed(seed)`
> > > > > > > > > `torch.manual_seed(seed)`
> > > > > > > > > `torch.cuda.manual_seed(seed)`
> > > > > > > > > `torch.cuda.manual_seed_all(seed)`
> > > > > > > > > I add the set_seed() function in train.py, but I cannot obtain the same results when I run the same code without any changes, do you know what's the problem?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > The randomness is not only related to the seed. You can check other factors in this [doc](https://pytorch.org/docs/stable/notes/randomness.html).
> > > > > > > > We fixed the seed to 0, however, it does not guarantee the same results runing on different machines.
> > > > > > > 
> > > > > > > 
> > > > > > > Hello! Thanks for your great work, I have experimented with your code on TACoS and Charades datasets you offered in google drive, but I met some problems on ActivityNet dataset. The download sh file in your repository seems invalid, and features on http://activity-net.org/challenges/2016/download.html , do not match with the json file you offered, can you offer some help?
> > > > > > 
> > > > > > 
> > > > > > Could you provide more information about what is not matched?
> > > > > 
> > > > > 
> > > > > If I directly use the features on the website http://activity-net.org/challenges/2016/download.html , there comes an error
> > > > > "**KeyError: "Unable to open object (object 'v_PdNb0g36a6U' doesn't exist)"**"
> > > > > The website notes that
> > > > > > We reduce the dimensionality of the activations from the second fully-connected layer (fc7) of our visual encoder from 4096 to 500 dimensions using PCA.  The C3D features were extracted every 8 frames
> > > > > 
> > > > > 
> > > > > Your paper mentioned that clip T is set to 16 for ActivityNet, how can I use the same feature you mentioned in your paper?
> > > > 
> > > > 
> > > > It seems like the provided features have been modified. Fortunately, I have a backup. You can check the shared google drive link again.
> > > 
> > > 
> > > hello, I tried to open the link, but the Activitynet folder seems to be locked, and I don't have the root to download it, I change to other accounts and failed too, can you give me the permission?
> > 
> > 
> > I just uploaded it again, you can try it now.
> 
> Thank you!!
> I saw you uploaded file 'sub_activitynet_v1-3.c3d.hdf5' first, then you uploaded 'activitynet_v1-3.part-*' and 'PCA_activitynet_v1-3.hdf5' files which is the same as the official features on http://activity-net.org/challenges/2017/download.html.
> Which feature was used in your paper? I saw the INPUT_SIZE in your activitynet yaml file is set to 500, is that mean you use c3d PCA features as ActivityNet input?

They are same. Yes, we use c3d PCA features.
