### ISSUE TITLE
Question about feature extraction.

### ISSUE THREAD

**Issue by DRJ2016** [microsoft/2D-TAN#26]
Sorry to disturb you. Really excellent work!
May I ask what Conv models to use for extracting frame features from raw videos?

**Comment by Sy-Zhang** [comment]
> Sorry to disturb you. Really excellent work!
> May I ask what Conv models to use for extracting frame features from raw videos?

For Charades, we use VGG features obtained from (here)[https://prior.allenai.org/projects/charades]
For ActivityNet, we use C3D features obtained from (here)[http://activity-net.org/challenges/2016/download.html]
For TACoS, we use use C3D features obtained from (here)[https://github.com/jiyanggao/TALL]
You can refer to their websites for more details about extraction.

**Comment by DRJ2016** [comment]
Really thank you for your reply.
