### ISSUE TITLE
About 2D-TAN for HACS Temporal Action Localization Challenge

### ISSUE THREAD

**Issue by DRJ2016** [microsoft/2D-TAN#28]
May I ask is there any implementation of S-2D-TAN for HACS on github? Really thank you.

**Comment by Sy-Zhang** [comment]
> May I ask is there any implementation of S-2D-TAN for HACS on github? Really thank you.

Sorry, we don't plan to release S-2D-TAN's code.

**Comment by DRJ2016** [comment]
Thank you!
