### ISSUE TITLE
Feature extractor problems

### ISSUE THREAD

**Issue by eedavidwu** [microsoft/2D-TAN#29]
Hi, may I ask about the method of feature extraction. 
Paper shows that the method is VGG16, but in the code, the features have been already given from the dataset, take Charades as example, it used Charades_v1_features_rgb.tar.gz.

For my own dataset,  do I need to train a two-stream net (like Two-Stream features  (RGB Stream) at first to extract the feature of the data? And then use the 2d-tan to localize the tasks.

**Comment by Sy-Zhang** [comment]
> Hi, may I ask about the method of feature extraction.
> Paper shows that the method is VGG16, but in the code, the features have been already given from the dataset, take Charades as example, it used Charades_v1_features_rgb.tar.gz.
> 
> For my own dataset, do I need to train a two-stream net (like Two-Stream features (RGB Stream) at first to extract the feature of the data? And then use the 2d-tan to localize the tasks.

Yes, you are right.
