### ISSUE TITLE
No module named pathlib

### ISSUE THREAD

**Issue by gtgtgt1117** [microsoft/2D-TAN#3]
Hello ,您代码更新完了嘛?我测试的时候报错

Traceback (most recent call last):
  File "moment_localization/test.py", line 20, in <module>
    from core.utils import AverageMeter
  File "/data/gao/2D-TAN/moment_localization/../lib/core/utils.py", line 8, in <module>
    from pathlib import Path
ImportError: No module named pathlib
这是什么,您可以告诉我一下.thankyou

**Comment by Sy-Zhang** [comment]
Did you run our code in python2? Our code should be run in python3, as mentioned in README.

**Comment by Sy-Zhang** [comment]
> Hello ,您代码更新完了嘛?我测试的时候报错
> 
> Traceback (most recent call last):
> File "moment_localization/test.py", line 20, in
> from core.utils import AverageMeter
> File "/data/gao/2D-TAN/moment_localization/../lib/core/utils.py", line 8, in
> from pathlib import Path
> ImportError: No module named pathlib
> 这是什么,您可以告诉我一下.thankyou

Did you run our code in python2? Our code should be run in python3, as mentioned in README.

**Comment by gtgtgt1117** [comment]
> > Hello ,您代码更新完了嘛?我测试的时候报错
> > Traceback (most recent call last):
> > File "moment_localization/test.py", line 20, in
> > from core.utils import AverageMeter
> > File "/data/gao/2D-TAN/moment_localization/../lib/core/utils.py", line 8, in
> > from pathlib import Path
> > ImportError: No module named pathlib
> > 这是什么,您可以告诉我一下.thankyou
> 
> Did you run our code in python2? Our code should be run in python3, as mentioned in README.

Thank you ! 现在可以了

**Comment by penghouwen** [comment]
@gtgtgt1117  problem was solved. closed.
