### ISSUE TITLE
Access denied when downloading features

### ISSUE THREAD

**Issue by mobraine** [microsoft/2D-TAN#30]
Is this link expired? Thanks! http://ai2-website.s3.amazonaws.com/data/Charades_v1_features_rgb.tar.gz

**Comment by Sy-Zhang** [comment]
Yes. You can download ``Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed)`` from their [website](https://prior.allenai.org/projects/charades).
