### ISSUE TITLE
Extracted features for TACos seem to be corrupted

### ISSUE THREAD

**Issue by tanchaolei** [microsoft/2D-TAN#31]
When using h5py.File("tall_c3d_features.hdf5", "r") to read the extracted features for TACos dataset, got error as follows:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 72876032, sblock->base_addr = 0, stored_eof = 485560344)

while I can open other hdf5 files normally, e.g. PCA_activitynet_v1-3.hdf5 can be read correctly. 
Is the TACos feature file corrupted? If so, can you please reupload tall_c3d_features.hdf5? 
Thanks a lot!

**Comment by Sy-Zhang** [comment]
I have downloaded ``tall_c3d_features.hdf5`` and it can be read correctly. Could you download it again?

**Comment by tanchaolei** [comment]
@Sy-Zhang I downloaded the file again and now it works correctly. I guess some part of tall_c3d_features.hdf5 was broken the first time I downloaded it. Thanks very much.
