### ISSUE TITLE
ActivityNet feature corrupted?

### ISSUE THREAD

**Issue by wjn922** [microsoft/2D-TAN#32]
Hi,

      Thanks for your great work and code. 
      The ActivityNet feature seems to be corrupted. I tried several times and it always has this problem. Could you please help?
![image](https://user-images.githubusercontent.com/21001460/115990604-bd377c00-a5f6-11eb-97d6-5b0ef2eeb369.png)

**Comment by Sy-Zhang** [comment]
> Hi,
> 
> ```
>   Thanks for your great work and code. 
>   The ActivityNet feature seems to be corrupted. I tried several times and it always has this problem. Could you please help?
> ```
> 
> ![image](https://user-images.githubusercontent.com/21001460/115990604-bd377c00-a5f6-11eb-97d6-5b0ef2eeb369.png)

I can download and extract the file correctly. Could you download it again?
