### ISSUE TITLE
Visual features

### ISSUE THREAD

**Issue by char-Fyzhao** [microsoft/2D-TAN#34]
Hello, I read your paper recently and your works were so amazing that I really want to reproduce it. But I have trouble in downloading the visual features from google drive becuase I don't have authority. I want to apply for authority for the visual features.

**Comment by Sy-Zhang** [comment]
> Hello, I read your paper recently and your works were so amazing that I really want to reproduce it. But I have trouble in downloading the visual features from google drive becuase I don't have authority. I want to apply for authority for the visual features.

The google drive links are expired now. I have pulled a request with the updated links. Please check it.

**Comment by char-Fyzhao** [comment]
I see,thanks
