### ISSUE TITLE
About your MS-2DTAN

### ISSUE THREAD

**Issue by Zzz512** [microsoft/2D-TAN#35]
Hi,i am interesting in your multi-scale 2D-TAN model because your result on TACoS improved significantly and the paper link point this code.But it seems two version share same code and i reproduced it get a worse performence.I wander if you update this code for your MS-2D-TAN model

**Comment by Sy-Zhang** [comment]
> Hi,i am interesting in your multi-scale 2D-TAN model because your result on TACoS improved significantly and the paper link point this code.But it seems two version share same code and i reproduced it get a worse performence.I wander if you update this code for your MS-2D-TAN model

We will release our code upon our paper's acceptance.

**Comment by Zzz512** [comment]
> > Hi,i am interesting in your multi-scale 2D-TAN model because your result on TACoS improved significantly and the paper link point this code.But it seems two version share same code and i reproduced it get a worse performence.I wander if you update this code for your MS-2D-TAN model
> 
> We will release our code upon our paper's acceptance.

OK,good luck~
