### ISSUE TITLE
Train and test using other video features

### ISSUE THREAD

**Issue by mobraine** [microsoft/2D-TAN#36]
Hello, thanks for the wonderful work! 

So I have some features that I extracted by myself and would like to train and test the network using those features, I wonder if you could let me know how to do this? I'm still using ActivityNet, Charades-STA and TACoS dataset but with different features. It would be even better if you could explain how to train the network on some completely different datasets!

Thanks in advance!

**Comment by Sy-Zhang** [comment]
> Hello, thanks for the wonderful work!
> 
> So I have some features that I extracted by myself and would like to train and test the network using those features, I wonder if you could let me know how to do this? I'm still using ActivityNet, Charades-STA and TACoS dataset but with different features. It would be even better if you could explain how to train the network on some completely different datasets!
> 
> Thanks in advance!

For ActivityNet, Charades-STA and TACoS, you just need to modify DATASET. VIS_INPUT_TYPE and TAN. FRAME_MODULE.PARAMS. INPUT_SIZE in the .yaml file. For other datasets, modifying the .yaml file would be enough.

**Comment by mobraine** [comment]
> 
> 
> > Hello, thanks for the wonderful work!
> > So I have some features that I extracted by myself and would like to train and test the network using those features, I wonder if you could let me know how to do this? I'm still using ActivityNet, Charades-STA and TACoS dataset but with different features. It would be even better if you could explain how to train the network on some completely different datasets!
> > Thanks in advance!
> 
> For ActivityNet, Charades-STA and TACoS, you just need to modify DATASET.VIS_INPUT_TYPE and TAN. FRAME_MODULE.PARAMS.INPUT_SIZE in the .yaml file. For other datasets, modifying the .yaml file would be eno

**Comment by mobraine** [comment]
Thanks!
