### ISSUE TITLE
about  rgb feature

### ISSUE THREAD

**Issue by jun0wanan** [microsoft/2D-TAN#37]
hi,

Thank you for your excellent work! I would like to ask if the original frame image you used is the 24fps on the charades' official website? (only Charades dataset) hope to get your reply ! thanks !

Best,
jun

**Comment by Sy-Zhang** [comment]
> hi,
> 
> Thank you for your excellent work! I would like to ask if the original frame image you used is the 24fps on the charades' official website? (only Charades dataset) hope to get your reply ! thanks !
> 
> Best,
> jun

We didn't extract features from raw images, but directly used Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed) provided by the offcial website.

**Comment by jun0wanan** [comment]
> > hi,
> > Thank you for your excellent work! I would like to ask if the original frame image you used is the 24fps on the charades' official website? (only Charades dataset) hope to get your reply ! thanks !
> > Best,
> > jun
> 
> We didn't extract features from raw images, but directly used Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed) provided by the offcial website.

hi,
    I want to know  function (sample_to_fixed_length ).. Why you use   average_to_fixed_length ?

**Comment by Sy-Zhang** [comment]
> > > hi,
> > > Thank you for your excellent work! I would like to ask if the original frame image you used is the 24fps on the charades' official website? (only Charades dataset) hope to get your reply ! thanks !
> > > Best,
> > > jun
> > 
> > 
> > We didn't extract features from raw images, but directly used Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed) provided by the offcial website.
> 
> hi,
> I want to know function (sample_to_fixed_length ).. Why you use average_to_fixed_length ?

Because average_to_fixed_length performs slightly better than sample_to_fixed_length.

**Comment by jun0wanan** [comment]
> > hi,
> > Thank you for your excellent work! I would like to ask if the original frame image you used is the 24fps on the charades' official website? (only Charades dataset) hope to get your reply ! thanks !
> > Best,
> > jun
> 
> We didn't extract features from raw images, but directly used Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed) provided by the offcial website.



> > > > hi,
> > > > Thank you for your excellent work! I would like to ask if the original frame image you used is the 24fps on the charades' official website? (only Charades dataset) hope to get your reply ! thanks !
> > > > Best,
> > > > jun
> > > 
> > > 
> > > We didn't extract features from raw images, but directly used Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed) provided by the offcial website.
> > 
> > 
> > hi,
> > I want to know function (sample_to_fixed_length ).. Why you use average_to_fixed_length ?
> 
> Because average_to_fixed_length performs slightly better than sample_to_fixed_length.

Do you mind to open this function code ? or maybe can give me a link ? ╥﹏╥...

**Comment by Sy-Zhang** [comment]
> > > hi,
> > > Thank you for your excellent work! I would like to ask if the original frame image you used is the 24fps on the charades' official website? (only Charades dataset) hope to get your reply ! thanks !
> > > Best,
> > > jun
> > 
> > 
> > We didn't extract features from raw images, but directly used Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed) provided by the offcial website.
> 
> > > > > hi,
> > > > > Thank you for your excellent work! I would like to ask if the original frame image you used is the 24fps on the charades' official website? (only Charades dataset) hope to get your reply ! thanks !
> > > > > Best,
> > > > > jun
> > > > 
> > > > 
> > > > We didn't extract features from raw images, but directly used Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed) provided by the offcial website.
> > > 
> > > 
> > > hi,
> > > I want to know function (sample_to_fixed_length ).. Why you use average_to_fixed_length ?
> > 
> > 
> > Because average_to_fixed_length performs slightly better than sample_to_fixed_length.
> 
> Do you mind to open this function code ? or maybe can give me a link ? ╥﹏╥...


```python
def sample_to_fixed_length(visual_input, random_sampling=False):
    num_sample_clips = config.DATASET.NUM_SAMPLE_CLIPS
    stride = config.DATASET.TARGET_STRIDE
    num_clips = visual_input.shape[0]

    if random_sampling:
        # random sample
        rand_idxs = torch.sort(torch.rand(stride, num_sample_clips//stride),dim=1)[0]
        rand_idxs = rand_idxs*num_clips/stride
        rand_idxs = rand_idxs+(torch.arange(0,stride,1.0)/stride*num_clips)[:,None]
        rand_idxs = torch.floor(rand_idxs).long().view(-1)
        rand_idxs = torch.min(rand_idxs, torch.tensor(num_clips-1))
    else:
        # equal interval
        rand_idxs = torch.arange(0,1,1/num_sample_clips)
        rand_idxs = torch.min(torch.round(rand_idxs*num_clips).long(), torch.tensor(num_clips-1))

    out_visual_input = visual_input[rand_idxs]

    return out_visual_input
```

**Comment by jun0wanan** [comment]
> > > > hi,
> > > > Thank you for your excellent work! I would like to ask if the original frame image you used is the 24fps on the charades' official website? (only Charades dataset) hope to get your reply ! thanks !
> > > > Best,
> > > > jun
> > > 
> > > 
> > > We didn't extract features from raw images, but directly used Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed) provided by the offcial website.
> > 
> > 
> > > > > > hi,
> > > > > > Thank you for your excellent work! I would like to ask if the original frame image you used is the 24fps on the charades' official website? (only Charades dataset) hope to get your reply ! thanks !
> > > > > > Best,
> > > > > > jun
> > > > > 
> > > > > 
> > > > > We didn't extract features from raw images, but directly used Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed) provided by the offcial website.
> > > > 
> > > > 
> > > > hi,
> > > > I want to know function (sample_to_fixed_length ).. Why you use average_to_fixed_length ?
> > > 
> > > 
> > > Because average_to_fixed_length performs slightly better than sample_to_fixed_length.
> > 
> > 
> > Do you mind to open this function code ? or maybe can give me a link ? ╥﹏╥...
> 
> ```python
> def sample_to_fixed_length(visual_input, random_sampling=False):
>     num_sample_clips = config.DATASET.NUM_SAMPLE_CLIPS
>     stride = config.DATASET.TARGET_STRIDE
>     num_clips = visual_input.shape[0]
> 
>     if random_sampling:
>         # random sample
>         rand_idxs = torch.sort(torch.rand(stride, num_sample_clips//stride),dim=1)[0]
>         rand_idxs = rand_idxs*num_clips/stride
>         rand_idxs = rand_idxs+(torch.arange(0,stride,1.0)/stride*num_clips)[:,None]
>         rand_idxs = torch.floor(rand_idxs).long().view(-1)
>         rand_idxs = torch.min(rand_idxs, torch.tensor(num_clips-1))
>     else:
>         # equal interval
>         rand_idxs = torch.arange(0,1,1/num_sample_clips)
>         rand_idxs = torch.min(torch.round(rand_idxs*num_clips).long(), torch.tensor(num_clips-1))
> 
>     out_visual_input = visual_input[rand_idxs]
> 
>     return out_visual_input
> ```

Thank you !!!!!!!!!!!!!!!!!!!  It was for the purpose of learning. Thank you very much for your sharing~ 

Maybe can you open  （interpolate_to_fixed_length） this function ?   

Best best,
wishes (●'◡'●)

**Comment by Sy-Zhang** [comment]
> interpolate_to_fixed_length

```python
def interpolate_to_fixed_length(visual_input):
    num_ori_clips = visual_input.shape[0]
    num_sample_clips = config.DATASET.NUM_SAMPLE_CLIPS
    sample_weight = torch.zeros(num_sample_clips, num_ori_clips)
    interpolate_value = torch.linspace(0,num_ori_clips-1, num_sample_clips)
    s_idx = torch.arange(0,num_sample_clips)
    el_idx = torch.floor(interpolate_value).long()
    er_idx = torch.floor(interpolate_value).long()+1
    sample_weight[s_idx, el_idx] = er_idx.float()-interpolate_value
    sample_weight[s_idx[:-1], er_idx[:-1]] = interpolate_value[:-1] - el_idx[:-1].float()
    out_visual_input = torch.mm(sample_weight, visual_input)

    return out_visual_input
```
Here you are.

**Comment by jun0wanan** [comment]
Thank you ! Best best wishes!
