### ISSUE TITLE
Training errors with new features

### ISSUE THREAD

**Issue by mobraine** [microsoft/2D-TAN#38]
Hello! 

I am trying to train the 2D-TAN network with my own extracted features of TACoS and I got the following error:

`Traceback (most recent call last):
  File "moment_localization/train.py", line 297, in <module>
    scheduler=scheduler)
  File "/home/share/wangzilong2/2D-TAN/moment_localization/../lib/core/engine.py", line 41, in train
    state['optimizer'].step(closure)
  File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/2D-TAN/lib/python3.7/site-packages/torch/optim/adam.py", line 58, in step
    loss = closure()
  File "/home/share/wangzilong2/2D-TAN/moment_localization/../lib/core/engine.py", line 30, in closure
    loss, output = state['network'](state['sample'])
  File "moment_localization/train.py", line 154, in network
    prediction, map_mask = model(textual_input, textual_mask, visual_input)
  File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/2D-TAN/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/share/wangzilong2/2D-TAN/moment_localization/../lib/models/tan.py", line 20, in forward
    vis_h = self.frame_layer(visual_input.transpose(1, 2))
  File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/2D-TAN/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/share/wangzilong2/2D-TAN/moment_localization/../lib/models/frame_modules/frame_pool.py", line 18, in forward
    vis_h = torch.relu(self.vis_conv(visual_input))
  File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/2D-TAN/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/2D-TAN/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 196, in forward
    self.padding, self.dilation, self.groups)

RuntimeError: Expected 3-dimensional input for 3-dimensional weight 256 2048 1 94911601578208 94911602548768 94911602553032, but got 6-dimensional input of size [256, 2048, 8, 2, 7, 7] instead`

My features (for each video, feature size is 64 * 2048) partially resemble the TACoS c3d features provided originally (for each video, feature size is x * 4096, where x stands for the varying number of clips used to extract features I think? but the point is they are different for each video) and they are both in hdf5 format. I have no idea what is wrong even after searching through the web, please help, thank you!

**Comment by Sy-Zhang** [comment]
> Hello!
> 
> I am trying to train the 2D-TAN network with my own extracted features of TACoS and I got the following error:
> 
> `Traceback (most recent call last):
> File "moment_localization/train.py", line 297, in
> scheduler=scheduler)
> File "/home/share/wangzilong2/2D-TAN/moment_localization/../lib/core/engine.py", line 41, in train
> state['optimizer'].step(closure)
> File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/2D-TAN/lib/python3.7/site-packages/torch/optim/adam.py", line 58, in step
> loss = closure()
> File "/home/share/wangzilong2/2D-TAN/moment_localization/../lib/core/engine.py", line 30, in closure
> loss, output = state['network'](state%5B'sample'%5D)
> File "moment_localization/train.py", line 154, in network
> prediction, map_mask = model(textual_input, textual_mask, visual_input)
> File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/2D-TAN/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/share/wangzilong2/2D-TAN/moment_localization/../lib/models/tan.py", line 20, in forward
> vis_h = self.frame_layer(visual_input.transpose(1, 2))
> File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/2D-TAN/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/share/wangzilong2/2D-TAN/moment_localization/../lib/models/frame_modules/frame_pool.py", line 18, in forward
> vis_h = torch.relu(self.vis_conv(visual_input))
> File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/2D-TAN/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/2D-TAN/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 196, in forward
> self.padding, self.dilation, self.groups)
> 
> RuntimeError: Expected 3-dimensional input for 3-dimensional weight 256 2048 1 94911601578208 94911602548768 94911602553032, but got 6-dimensional input of size [256, 2048, 8, 2, 7, 7] instead`
> 
> My features (for each video, feature size is 64 * 2048) partially resemble the TACoS c3d features provided originally (for each video, feature size is x * 4096, where x stands for the varying number of clips used to extract features I think? but the point is they are different for each video) and they are both in hdf5 format. I have no idea what is wrong even after searching through the web, please help, thank you!

as mentioned in RuntimeError, please check your input feature size.
