### ISSUE TITLE
about Upper Bound in Table 4

### ISSUE THREAD

**Issue by onlyonewater** [microsoft/2D-TAN#39]
hi, in the paper, you provide the upper bound results on `activitynet captioning ` dataset, I want to know how to calculate the upper bound results, thanks!!!

**Comment by Sy-Zhang** [comment]
For each map of size NxN, we assume the moment that has the highest IoU value with the ground truth is our prediction. The upper bound can then be computed.

**Comment by onlyonewater** [comment]
oh, I get it. thanks!!!!
