### ISSUE TITLE
video feature

### ISSUE THREAD

**Issue by YongdongTan** [microsoft/2D-TAN#40]
What is your model for extracting visual features?

**Comment by Sy-Zhang** [comment]
> What is your model for extracting visual features?

Please check our paper for details.

**Comment by YongdongTan** [comment]
> > What is your model for extracting visual features?
> 
> Please check our paper for details.

Glad you can answer，I learned from the paper that c3d is used when extracting video features. I want to know how this c3d is trained, I have the activitynet data set, and I want to test it through the original video

**Comment by Sy-Zhang** [comment]
> > > What is your model for extracting visual features?
> > 
> > 
> > Please check our paper for details.
> 
> Glad you can answer，I learned from the paper that c3d is used when extracting video features. I want to know how this c3d is trained, I have the activitynet data set, and I want to test it through the original video

Please check this issue #26

**Comment by Sy-Zhang** [comment]
Please check issue #53 for further information.
