### ISSUE TITLE
about TACoS data split

### ISSUE THREAD

**Issue by sangminwoo** [microsoft/2D-TAN#41]
Hi @Sy-Zhang!
Appreciate for providing a nicely organized codebase.

I am confused about the data split regarding the TACoS dataset.
While your paper indicates that it follows the data split of TALL (Gao et al. 2017), I found they are not the same.
The data split in TALL is 50:25:25 (proportion) and your code is 75/27/25 (actual number), which is obviously different.
It would be more clear if you clarify the one practitioners to follow.

Many thanks.

**Comment by Sy-Zhang** [comment]
> Hi @Sy-Zhang!
> Appreciate for providing a nicely organized codebase.
> 
> I am confused about the data split regarding the TACoS dataset.
> While your paper indicates that it follows the data split of TALL (Gao et al. 2017), I found they are not the same.
> The data split in TALL is 50:25:25 (proportion) and your code is 75/27/25 (actual number), which is obviously different.
> It would be more clear if you clarify the one practitioners to follow.
> 
> Many thanks.

If you check the annotation files in TALL, there should be 10146, 4589, 4083 samples in the training, validation and testing sets.

**Comment by sangminwoo** [comment]
Oh, I see... I got it thanks!
