### ISSUE TITLE
ValueError: DATA_DIR not exist in config.py

### ISSUE THREAD

**Issue by JackyWang2001** [microsoft/2D-TAN#49]
Hi, Sy. I am trying to run MS-2D-TAN with `python moment_localization/train.py --cfg experiments/tacos/MS-2D-TAN-G-VGG.yaml --dataDir data/ --verbose` but get the following error: 
```
Traceback (most recent call last):
  File "moment_localization/train.py", line 77, in <module>
    args = parse_args()
  File "moment_localization/train.py", line 43, in parse_args
    update_config(args.cfg)
  File "/media/jpl/T7/MS-2D-TAN/lib/core/config.py", line 105, in update_config
    _update_dict(config[k], v)
  File "/media/jpl/T7/MS-2D-TAN/lib/core/config.py", line 96, in _update_dict
    raise ValueError("{} not exist in config.py".format(k))
ValueError: DATA_DIR not exist in config.py
```
For clarification, since my environment reported error on import. I changed the code in `train.py` (but I dont think the problem is here): 
```
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from lib import models
from lib import datasets
from lib.core.config import config, update_config
...
```

**Comment by Sy-Zhang** [comment]
As I mention

> Hi, Sy. I am trying to run MS-2D-TAN with `python moment_localization/train.py --cfg experiments/tacos/MS-2D-TAN-G-VGG.yaml --dataDir data/ --verbose` but get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "moment_localization/train.py", line 77, in <module>
>     args = parse_args()
>   File "moment_localization/train.py", line 43, in parse_args
>     update_config(args.cfg)
>   File "/media/jpl/T7/MS-2D-TAN/lib/core/config.py", line 105, in update_config
>     _update_dict(config[k], v)
>   File "/media/jpl/T7/MS-2D-TAN/lib/core/config.py", line 96, in _update_dict
>     raise ValueError("{} not exist in config.py".format(k))
> ValueError: DATA_DIR not exist in config.py
> ```
> 
> For clarification, since my environment reported error on import. I changed the code in `train.py` (but I dont think the problem is here):
> 
> ```
> import sys
> sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
> from lib import models
> from lib import datasets
> from lib.core.config import config, update_config
> ...
> ```

As I mentioned in README.md, the command should start with `python moment_localization/run.py ...`. I have removed `moment_localization/train.py` and `moment_localization/test.py` since they belong to 2D-TAN but not MS-2D-TAN. Sorry for confusing you.

**Comment by JackyWang2001** [comment]
Thanks for your timely reply and clarification. I should read the README more carefully.
