### ISSUE TITLE
About TACoS data annotation

### ISSUE THREAD

**Issue by zjr2000** [microsoft/2D-TAN#50]
Hi @Sy-Zhang 
Thank you for your excellent work! 
I am confused about the annotation in TACoS, cause some of the annotations you provide are different from [officially provided](https://www.coli.uni-saarland.de/projects/smile/page.php?id=tacos).

For example, for the video s13-d21.avi in train.json, timestamp [252, 686] appears in your annotations but not in the original annotations. I‘d appreciate it if you could explain that.

**Comment by Sy-Zhang** [comment]
> Hi @Sy-Zhang Thank you for your excellent work! I am confused about the annotation in TACoS, cause some of the annotations you provide are different from [officially provided](https://www.coli.uni-saarland.de/projects/smile/page.php?id=tacos).
> 
> For example, for the video s13-d21.avi in train.json, timestamp [252, 686] appears in your annotations but not in the original annotations. I‘d appreciate it if you could explain that.

I guess you are using TACoS/alignments-text/**-**.aligned.tsv in the offical repo. For all my experiments, I use the annotations from TACoS/index/**-**.sentences.tsv.

**Comment by zjr2000** [comment]
> > Hi @Sy-Zhang Thank you for your excellent work! I am confused about the annotation in TACoS, cause some of the annotations you provide are different from [officially provided](https://www.coli.uni-saarland.de/projects/smile/page.php?id=tacos).
> > For example, for the video s13-d21.avi in train.json, timestamp [252, 686] appears in your annotations but not in the original annotations. I‘d appreciate it if you could explain that.
> 
> I guess you are using TACoS/alignments-text/*-*.aligned.tsv in the offical repo. For all my experiments, I use the annotations from TACoS/index/*-*.sentences.tsv.

I got it! Thanks for your reply~.
