### ISSUE TITLE
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = './data/Charades-STA/vgg_rgb_features.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by thomasren681** [microsoft/2D-TAN#51]
Greetings! 
I'm currently trying to run and train this model, but I've encountered some problems relating to the dataset.
I've followed the instruction to download the Charades_v1_features_rgb.tar.gz from the official website and converted it to charades_vgg_rgb.hdf5. However, the error occurred saying that I don't have the file vgg_rgb_features.hdf5. 
I wonder do I have to download this from the box drive link in the README.md? Since the download always seems to fail, I want to know whether it will work the same if I change the output file name to vgg_rgb_features.hdf5 instead of charades_vgg_rgb.hdf5 in the convert_vgg_features_to_hdf5.py?

**Comment by Sy-Zhang** [comment]
Yes, you can rename to vgg_rgb_features.hdf5. They are the same.

**Comment by thomasren681** [comment]
> > Greetings! I'm currently trying to run and train this model, but I've encountered some problems relating to the dataset. I've followed the instruction to download the Charades_v1_features_rgb.tar.gz from the official website and converted it to charades_vgg_rgb.hdf5. However, the error occurred saying that I don't have the file vgg_rgb_features.hdf5. I wonder do I have to download this from the box drive link in the README.md? Since the download always seems to fail, I want to know whether it will work the same if I change the output file name to vgg_rgb_features.hdf5 instead of charades_vgg_rgb.hdf5 in the convert_vgg_features_to_hdf5.py?
> 
> Yes, you can rename to vgg_rgb_features.hdf5. They are the same.

Thanks for replying, I'm glad that this works.
