### ISSUE TITLE
About the feature extraction

### ISSUE THREAD

**Issue by zzxihuanheixiu** [microsoft/2D-TAN#53]

**Comment by zzxihuanheixiu** [comment]
Hello, although I followed up the link in the issue, I still don't know the specific details of your video clip feature extraction. If it's convenient, please provide the code for extracting clip features. I want to study it carefully.
Sincere thanks!

**Comment by Sy-Zhang** [comment]
> Hello, although I followed up the link in the issue, I still don't know the specific details of your video clip feature extraction. If it's convenient, please provide the code for extracting clip features. I want to study it carefully. Sincere thanks!

For our conference paper, please check issue #26 for details.
For our journal paper, the details are listed here.
**Charades** 
- VGG: download from [here](https://prior.allenai.org/projects/charades).
- C3D: download from [here](https://github.com/JaywongWang/CBP)
- I3D: download from [here](https://github.com/yytzsy/SCDM)
- I3D finetuned: we finetune i3d with this [codebase](https://github.com/piergiaj/pytorch-i3d)

**ActivityNet** 
- C3D: download from [here](https://github.com/yytzsy/SCDM)
- I3D: download from [here](https://github.com/Finspire13/CMCS-Temporal-Action-Localization)

**TACoS**
- VGG: we use pretrained VGG16 from torchvision.models.
- C3D: download from [here](https://github.com/yytzsy/SCDM)
- I3D: we extract i3d with this [codebase](https://github.com/piergiaj/pytorch-i3d)
