### ISSUE TITLE
should the txt be ordered in the convert_vgg_features_to_hdf5.py

### ISSUE THREAD

**Issue by liu666666** [microsoft/2D-TAN#6]
Hi，@penghouwen，@Sy-Zhang  Thanks for sharing the nice job!

I had a question: should the txt be ordered in the convert_vgg_features_to_hdf5.py? If these texts not ordered, we cannot get the right video temporal information. 

Please correct me if I am wrong. Thank you again for your nice work!

**Comment by Sy-Zhang** [comment]
Hi @liu666666 ,
Thank you very much for point it out. I have fixed this bug and pull the request. I also upload the generated h5 file and the the models trained on the updated features. Please check readme for more details.
