### ISSUE TITLE
The onedrive link for downloading features is expired

### ISSUE THREAD

**Issue by Xun-Yang** [microsoft/2D-TAN#7]
Hi, Thanks for sharing such good work.

 I just found the onedirve link for feature download is expired. Could you repair it asap ?

Regards

**Comment by onlyonewater** [comment]
I got the same problem？Did you solve it?

**Comment by Sy-Zhang** [comment]
I just pull a request for updating the data and checkpoint links, please check it.

**Comment by onlyonewater** [comment]
@Sy-Zhang ，Thanks a lot !!!

**Comment by penghouwen** [comment]
Done.
