### ISSUE TITLE
Extract Features

### ISSUE THREAD

**Issue by onlyonewater** [microsoft/2D-TAN#9]
Hi,In Google Drive,there are just the extract features of tacos and Charades-STA datasets,Do you have the extract features of activitynet dataset??Thanks

**Comment by Sy-Zhang** [comment]
Please refer to ```data/ActivityNet/download.sh``` in this repo.  These features are  provided in http://activity-net.org/challenges/2016/download.html.

**Comment by onlyonewater** [comment]
OK,I know, thanks
