### ISSUE TITLE
[X-CLIP] Now it's no drop_out in clip?

### ISSUE THREAD

**Issue by laisimiao** [microsoft/2D-TAN#90]
I see 
https://github.com/microsoft/VideoX/blob/1f07a646e3b989d2c39b725944217597deb31be9/X-CLIP/models/cct.py#LL8C50-L8C50
but in clip(openai) source code, they do not use drop_out operation and no `DropPath` module can be loaded from `clip.model`, could you explain the reason, thanks so much!

**Comment by laisimiao** [comment]
@nbl97

**Comment by nbl97** [comment]
Thanks for your interest. DropPath is a common technique used to overcome the overfitting in training large models. We add this skill to the codebase, but eventually we do not use that, i.e., the drop_path_rate is set to 0.
